"use strict";var o=require("atom"),e="open-in-developer-mode";
/*! *****************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */
function t(o,e){for(var t=0,n=e.length,a=o.length;t<n;t++,a++)o[a]=e[t];return o}var n=new(function(){function o(o){void 0===o&&(o={}),this.name=o.name,this.styleSheet="\n      background-color: "+(o.backgroundColor||"darkgrey")+";\n      border-radius: 2px;\n      color: "+(o.color||"white")+";\n      line-height: 1.5;\n      padding: 1px 4px;\n      text-shadow: 0 1px 0px rgba(0, 0, 0, 0.2);\n    "}return o.prototype.__console__=function(o){for(var e,t=[],n=1;n<arguments.length;n++)t[n-1]=arguments[n];(null===atom||void 0===atom?void 0:atom.inDevMode())&&(t.unshift("%c"+this.name+"%c",this.styleSheet,""),(e=window.console)[o].apply(e,t))},o.prototype.debug=function(){for(var o=[],e=0;e<arguments.length;e++)o[e]=arguments[e];this.__console__.apply(this,t(["debug"],o))},o.prototype.error=function(){for(var o=[],e=0;e<arguments.length;e++)o[e]=arguments[e];this.__console__.apply(this,t(["error"],o))},o.prototype.info=function(){for(var o=[],e=0;e<arguments.length;e++)o[e]=arguments[e];this.__console__.apply(this,t(["info"],o))},o.prototype.log=function(){for(var o=[],e=0;e<arguments.length;e++)o[e]=arguments[e];this.__console__.apply(this,t(["log"],o))},o.prototype.trace=function(){for(var o=[],e=0;e<arguments.length;e++)o[e]=arguments[e];this.__console__.apply(this,t(["trace"],o))},o.prototype.warn=function(){for(var o=[],e=0;e<arguments.length;e++)o[e]=arguments[e];this.__console__.apply(this,t(["warn"],o))},o}())({name:e,backgroundColor:"mediumaquamarine"});function a(){var o,e=atom.project.getPaths();if(null==e?void 0:e.length)return n.log("Found project paths"),e;var t=null===(o=atom.workspace.getActiveTextEditor())||void 0===o?void 0:o.getPath();return(null==t?void 0:t.length)?(n.log("Found text editor path"),[t]):(n.warn("No paths founds"),[])}var i={subscriptions:new o.CompositeDisposable,activate:function(){n.log("Activating package"),this.subscriptions.add(atom.commands.add("atom-workspace",{"open-in-developer-mode:open":function(){!function(){if(!atom.inDevMode()){var o=a();return n.log("Opening paths developer mode",o),atom.open({pathsToOpen:o,newWindow:!1,devMode:!0})}atom.notifications.addInfo("You're already in Developer Mode",{dismissable:!1})}()}}),atom.commands.add("atom-workspace",{"open-in-developer-mode:toggle":function(){var o;(null==(o=a())?void 0:o.length)?(n.log("Opening paths "+(atom.inDevMode()?"developer":"normal")+" mode",o),atom.open({pathsToOpen:o,newWindow:!1,devMode:!atom.inDevMode()})):atom.commands.dispatch(atom.views.getView(atom.workspace),"application:open-dev")}}))},deactivate:function(){var o;n.log("Deactivating package"),null===(o=this.subscriptions)||void 0===o||o.dispose()}};module.exports=i;
//# sourceMappingURL=main.js.map
